### PR TITLE
chore(icon): update icon

### LINKED ISSUE #476: Update Cryostat icon for bundle

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #476

### CODE REVIEW

**Review by ebaron — COMMENTED** [review]
Edit: wrong PR

**Comment by andrewazores** [comment]
> The image for the bundle is actually the base64-encoded SVG file:

Right you are, I remembered that this morning before logging on. I'll fix it soon.

**Review by ebaron — COMMENTED** [review]
Icon looks good, could you run `make bundle`?

**Review by ebaron — APPROVED** [review]
Thanks!

**Pull request merged**
