### PR TITLE
fix(build-ci): fix scorecard image tag returned as null

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Related to #698 

## Description of the change:

Updated CI to get scorecard tag from the 2nd test stage (custom scorecard) added in #698.

## Motivation for the change:

The scorecard image is being built with tag `null` on upstream main.

CI: https://github.com/cryostatio/cryostat-operator/actions/runs/8161839436/job/22311468196

Quay: https://quay.io/repository/cryostat/cryostat-operator-scorecard?tab=tags

### CODE REVIEW

**Review by andrewazores — APPROVED** [review]

**Review by ebaron — APPROVED** [review]
Thanks for noticing and fixing the problem Thuan!

**Comment by ebaron** [comment]
@Mergifyio backport cryostat3

**Comment by tthvo** [comment]
https://github.com/cryostatio/cryostat-operator/actions/runs/8302678684/job/22725444182

```bash
Image:      ghcr.io/cryostatio/cryostat-operator-scorecard:ci-2201704822677f0e1ad94fee0d64250a7af2e67c
Entrypoint: [cryostat-scorecard-tests operator-install]
Labels:
	"test":"operator-install"
	"suite":"cryostat"
Results:
	State: fail

	Errors:
		pods "scorecard-test-x697" already exists
```

Randomized pod's name just happens to conflict? It's probably not our end...

**Comment by ebaron** [comment]
That's really weird. You're right though, the scorecard-test pods are managed by Operator SDK.

**Comment by tthvo** [comment]
https://github.com/operator-framework/operator-sdk/blob/4abd483aa4004af83b3c05ddf9d7a7e4d4653cc7/internal/scorecard/testpod.go#L41

Haha right. Maybe, another day of random not being actual so random :D

**Pull request merged**
