### PR TITLE
docs(deploy): add instructions on how to obtain static manifests

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #901 
Fixes: #144 

## Description of the change:

- Added instructions on how to obtain static manifests

Note: `kubectl apply -f` would fail due to annotation size limit. Use `kubectl create -f` instead.

## Motivation for the change:

See #901.  A single static manifest that is bundled with all k8s resources allows users to install the operator with `kubectl apply/create -f <manifest-url>`. This aligns with common practice on upstream k8s.

## How to manually test:

You can follow the instructions in README.

### CODE REVIEW

**Comment by tthvo** [comment]
This is a pretty (maybe too) simple solution. It uses the hard-coded namespace `cryostat-operator-system` that the user must create in-advance. I am thinking 2 possible ways around it:

- Maybe use a commonly available namespace like `default`?
- Or remove the namespace field? I am a bit unsure how to do this with kustomize.

**Review by andrewazores — COMMENTED** [review]
I think it'd be nice to have this static manifest kept up-to-date automatically by some git commit hook or a GH action. Otherwise it's too easy to forget to update this and have it fall out of date with the rest of the sources it's meant to correspond to.

I think I would also still rather have it published some other way/place than having it checked in to the source repo. It is after all just a generated artifact, which can be reproduced from any given source repo commit. So checking it in to the repository only seems to serve the purpose of making it accessible via a GitHub URL.

**Comment by andrewazores** [comment]
> Or maybe it does not matter much since others (e.g. ingress-nginx, cert-manager) use a specific namespace anyway. That being said, perhaps the YAML for namespace cryostat-operator-system should also be included in the static file?

Being completely honest, I think at some point if more customization and functionality is needed, then the end user needs to either use the Operator or Helm Chart, or they need to be comfortable modifying the static manifest file to suit their needs. It's likely that users have their own particular details to suit their own particular deployment scenarios, so we should make sure that it's possible for them to achieve what they need to, but carrying all of the customizations upstream seems a bit too much. I fear that if we add the namespace customization feature to the static manifest, then we will also be asked to add other features to the static manifest, and then we are just re-inventing the Helm Chart again.

**Comment by tthvo** [comment]
> > Or maybe it does not matter much since others (e.g. ingress-nginx, cert-manager) use a specific namespace anyway. That being said, perhaps the YAML for namespace cryostat-operator-system should also be included in the static file?
> 
> Being completely honest, I think at some point if more customization and functionality is needed, then the end user needs to either use the Operator or Helm Chart, or they need to be comfortable modifying the static manifest file to suit their needs. It's likely that users have their own particular details to suit their own particular deployment scenarios, so we should make sure that it's possible for them to achieve what they need to, but carrying all of the customizations upstream seems a bit too much. I fear that if we add the namespace customization feature to the static manifest, then we will also be asked to add other features to the static manifest, and then we are just re-inventing the Helm Chart again.

Now, looking back, I proposed this solution before discovering we can use URL with kustomize: https://github.com/cryostatio/cryostat-operator/issues/901#issuecomment-2195766199. How about instead of this, I document that it is possible gain static manifests (out of `make deploy` without actually apply them to k8s)?

```bash
# Replace ref with any version tag or branch
kubectl kustomize https://github.com/cryostatio/cryostat-operator.git/config/default?ref=v2.4.0 | kubectl create -f
```

This way, we can avoid it all together to add more maintenance efforts.

**Review by andrewazores — APPROVED** [review]

**Review by ebaron — APPROVED** [review]

**Comment by ebaron** [comment]
Thanks @tthvo!

**Pull request merged**
