### PR TITLE
feat(scorecard): allow running scorecard test locally

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #775 

## Description of the change:

Modify scorecard to allow running scorecard test locally.
- Update to use `config.GetConfig` to also pick local kube configurations (e.g. ` $HOME/.kube/config`)
- Allow overwriting bundle path with `BUNDLE_DIR`.

**Note:** This requires the cluster to be reachable from the host (e.g. local OpenShift with `crc`). Setup with `kind` and `podman` is not supported as host is not interfaced with the cluster network (but `kind` and `docker` should work).

## Motivation for the change:

This makes it easier to run scorecard without having to rebuild the scorecard and bundle images.

## How to manually test:

Assuming local host is properly configured to communicate with a k8s cluster. See https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/config#GetConfig

If using `crc`:

```bash
crc start
oc login -u kubeadmin
```

Run the scorecard locally:

```bash
export SCORECARD_NAMESPACE=cryostat-operator-scorecard
export BUNDLE_DIR=./bundle
kubectl create ns $SCORECARD_NAMESPACE
kubectl config set-context --current --namespace $SCORECARD_NAMESPACE
make deploy_bundle
go run internal/images/custom-scorecard-tests/main.go cryostat-recording
```

Note: Replace `cryostat-recording` with any support test names (e.g. `operator-install`,`cryostat-cr,cryostat-multi-namespace`)

### CODE REVIEW

**Comment by andrewazores** [comment]
> go run internal/images/custom-scorecard-tests/main.go cryostat-recording

> Note: Replace cryostat-recording with any support test names (e.g. operator-install,cryostat-cr,cryostat-multi-namespace)

I think this could be made a little friendler with a simple makefile target, so it could be run like `make test-scorecard-local SCORECARD_TEST_SELECTION=cryostat-recording`. This way the `SCORECARD_TEST_SELECTION`/`SCORECARD_TEST_SELECTOR` variable can be reused between the two different modes of running the tests, and it's a bit easier to remember that the tests can be run this way too.

**Comment by tthvo** [comment]
To run tests with auto & fresh setup everytime:

```bash
SCORECARD_TEST_SELECTION=cryostat-cr,cryostat-recording make test-scorecard-local
```

To run tests only with existing controller deployment:

```bash
SCORECARD_TEST_ONLY=true SCORECARD_TEST_SELECTION=cryostat-cr,cryostat-recording make test-scorecard-local
```

This is helpful when you want to run tests repeatedly. How about now?

**Review by andrewazores — APPROVED** [review]
@ebaron any objection?

**Review by ebaron — APPROVED** [review]
Great, thanks @tthvo! This should speed up development of the scorecard tests

**Pull request merged**
