### PR TITLE
fix(deploy): set CRYOSTAT_SSL_PROXIED only for TLS ingress/route

### LINKED ISSUE #293: Web UI WebSocket Error
Deployment to Azure Kubernetes Service as well as to Docker Desktop Kubernetes results in inability to login and a lot of WebSocker Error messages in the UI.

websocket-error

Docker Desktop Kubernetes version: `v1.19.7`
AKS version: `v1.20.5`

**Steps to reproduce:**

* Create namespace: `kubectl create namespace cryostat-operator-system`
* Deploy Operator: `kubectl apply -k 'github.com/cryostatio/cryostat-operator//config/default?ref=v2.0.0'`
* Deploy Cryostat:
```bash
cat <<EOF | kubectl apply -n cryostat-operator-system -f -
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-test
spec:
  minimal: false
  enableCertManager: false
EOF
```
* Port-forward to cryostat pod: `kubectl port-forward -n cryostat-operator-system pod/cryostat-test-9cb696549-zdkp7 8181 9090 3000`

I can see the same issue with Ingress configured on AKS - the following configuration:

```yaml
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-test
spec:
  minimal: false
  enableCertManager: false
  networkOptions:
    coreConfig:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        nginx.org/websocket-services: cryostat-test
      ingressSpec:
        rules:
        - host: cryostat.my-private-domain.azure
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-test
                  port:
                    number: 8181
    commandConfig:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        nginx.org/websocket-services: cryostat-command
      ingressSpec:
        rules:
        - host: cryostat-command.my-private-domain.azure
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-command
                  port:
                    number: 9090
    grafanaConfig:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        nginx.org/websocket-services: cryostat-grafana
      ingressSpec:
        rules:
        - host: cryostat-grafana.my-private-domain.azure
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-grafana
                  port:
                    number: 3000
```

Also the specified annotations are not applied to the Ingress resources for some reason.

**Expected results:**

I should be able to successfully login with the credentials from Kubernetes Secrets resource.

### PR DESCRIPTION
**Pull request by ebaron**
This modifies the deployment spec to only set `CRYOSTAT_SSL_PROXIED` when cert-manager is disabled, but the Route/Ingress use TLS. I've added a test for this scenario with Ingress, currently Routes are always created with TLS.

Related to: #293

### CODE REVIEW

**Comment by ebaron** [comment]
Tested in minikube with `$(minikube ip) testing.cryostat testing.cryostat-command testing.cryostat-grafana` added to `/etc/hosts` and the following CR:
```yaml
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-sample
spec:
  minimal: false
  enableCertManager: false
  trustedCertSecrets: []
  storageOptions:
    pvc:
      labels: {}
      annotations: {}
      spec: {}
  networkOptions:
    coreConfig:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      ingressSpec:
        rules:
        - host: testing.cryostat
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-sample
                  port:
                    number: 8181
    commandConfig:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      ingressSpec:
        rules:
        - host: testing.cryostat-command
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-sample-command
                  port:
                    number: 9090
    grafanaConfig:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      ingressSpec:
        rules:
        - host: testing.cryostat-grafana
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-sample-grafana
                  port:
                    number: 3000
```

I now receive the following WebSocket error every minute:
```
12:25:47.616 undefined NotificationChannel.service.tsx:224:19
    logError NotificationChannel.service.tsx:224
    error NotificationChannel.service.tsx:196
    RxJS 14
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 8
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 8
    next NotificationChannel.service.tsx:194
    RxJS 13
    checkAuth Login.service.tsx:109
    RxJS 7
```

**Comment by andrewazores** [comment]
Looks like that means the web-client is still failing to establish its WebSocket connection:

https://github.com/cryostatio/cryostat-web/blob/main/src/app/Shared/Services/NotificationChannel.service.tsx#L224

Too bad we aren't getting any more information about the error from the browser. What does your browser's devtools Network tab show when it makes connection attempts? Is the protocol using `ws/wss`/`http/https` as expected, or as matching `curl $cryostat/api/v1/notifications_url`? I wonder if the hostname resolution might also still be failing.

**Comment by ebaron** [comment]
It's returning `ws://testing.cryostat:80/api/v1/notifications` which looks correct.

**Comment by ebaron** [comment]
The web client is using that URL as well, and getting this response:
`{"meta":{"category":"WsClientActivity","type":{"type":"application","subType":"json"},"serverTime":1636572394},"message":{"172.17.0.2:43696":"accepted"}}`

Before I receive the above error, I also see this appear once:
```
14:30:59.640 {} Login.service.tsx:116:23
    checkAuth Login.service.tsx:116
    RxJS 55
        innerSub
        _error
        error
        _error
        error
        tap
        _error
        error
        _error
        error
        _error
        error
        _error
        error
        fromPromise
        (Async: promise callback)
    fromPromise
        _trySubscribe
        subscribe
        errorContext
        subscribe
        doInnerSub
        outerNext
        _next
        next
        fromFetch
        (Async: promise callback)
    fromFetch
        _trySubscribe
        subscribe
        errorContext
        subscribe
        mergeInternals
        mergeMap
        operate
        subscribe
        errorContext
        subscribe
        take
        operate
        subscribe
        errorContext
        subscribe
        throwIfEmpty
        operate
        subscribe
        errorContext
        subscribe
        tap
        operate
        subscribe
        errorContext
        subscribe
        map
        operate
        subscribe
        errorContext
```

**Comment by andrewazores** [comment]
Perhaps we're using different `CORE_VERSION`s, but I see a websocket error in the console after some time with a trace like this:

```
 NotificationChannel.service.tsx:224:19
    logError NotificationChannel.service.tsx:224
    error NotificationChannel.service.tsx:196
    RxJS 14
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 8
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 8
    next NotificationChannel.service.tsx:194
    RxJS 13
    setSessionState Login.service.tsx:184
    next NotificationChannel.service.tsx:188
    RxJS 6
```

Initially the websocket connection opens fine and I receive notifications as expected when doing things like starting recordings, so I'm not sure why the connection closes and fails to reopen later on.

**Comment by andrewazores** [comment]
I've filed a web-client issue for the `NotificationChannel` failure we're observing. That looks to me very much like a web-client error handling problem and not something to do with the Operator changes made in this PR.

**Review by andrewazores — APPROVED** [review]
After some struggle to get Minikube set up properly for myself, I was able to test this PR and observe that a setup without cert-manager and with `DISABLE_SERVICE_TLS=true` led to a Cryostat deployment without `CRYOSTAT_SSL_PROXIED` set, with the net result being that Cryostat reports its various URLs as the non-SSL versions (ex `ws://` for the notifications channel). Working as intended.

**Pull request merged**
