### PR TITLE
chore(rename): update references after repo rename

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Related to https://github.com/cryostatio/cryostat/pull/555
Related to https://github.com/cryostatio/cryostat-helm/pull/159

## Description of the change:
*This change adds allows the users to provide...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Insert steps here...*
2. *...*

### CODE REVIEW

**Review by ebaron — COMMENTED** [review]
Do you know if this would cause any problems when upgrading?

**Comment by andrewazores** [comment]
I imagine that it will break things on upgrade, but the next version is already likely to break things on upgrade anyway since we're scoping in work like https://github.com/cryostatio/cryostat/issues/549 and https://github.com/cryostatio/cryostat-operator/issues/814 . I'm hoping that putting all those pieces together in the next release means that we can have a better migration/upgrade path from that point on.

**Review by ebaron — APPROVED** [review]
Sounds good

**Pull request merged**
