### PR TITLE
test(scorecard): fix failing built-in olm scorecard test

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #865 

## Description of the change:

- Modified `alm-examples` annotation of CSV to include only v1beta2.
- Use `yq`'s `reverse` operator for explicit list reversing (just cleaner than using `pick`).

## Motivation for the change:

See #865

### CODE REVIEW

**Comment by tthvo** [comment]
Closing as it seems operator-sdk is causing the issue.

**Comment by tthvo** [comment]
There would be a warning when generating the bundle but validation passes and tests also pass.

```
WARN[0000] Warning: Value operator.cryostat.io/v1beta1, Kind=Cryostat: provided API should have an example annotation 
INFO[0000] All validation tests have completed successfully 
```

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
