### PR TITLE
build(version): update versions for 2.2.1-dev

### PR DESCRIPTION
**Pull request by ebaron**
Related to: https://github.com/cryostatio/cryostat/issues/1118

### CODE REVIEW

**Review by andrewazores — COMMENTED** [review]
lgtm

**Review by tthvo — APPROVED** [review]
Looks good to me! Just wondering about the choice of image tags here? Why `snapshot` and `cryostat-` (only Grafana?)?

**Comment by tthvo** [comment]
Right that makes sense! Thanks for explaining :D

**Comment by ebaron** [comment]
> Right that makes sense! Thanks for explaining :D

No problem, I filed https://github.com/cryostatio/cryostat-grafana-dashboard/issues/19 in response to this discussion.

**Pull request merged**
