### PR TITLE
build(cert-manager): upgrade cert-manager version

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #484 

## Description of the change:

Upgrade cert-manager to `1.11.5`. I selected this version to match the Go module version (`1.11.1`), but went with this patch because it included CVE fixes.

Releases: https://github.com/cert-manager/cert-manager/releases?q=1.11.&expanded=true

## Motivation for the change:

Cert Manager >= 1.10 includes fixes that ensures pods are able to run under restricted policy.

### CODE REVIEW

**Comment by andrewazores** [comment]
@tthvo I see your commits are signed but unverified. This usually means that your GPG setup on your workstation is working correctly and signing commits, but your GitHub profile is missing information to match up with those commit signatures - either the GPG public key needs to be added to your profile, or I think this may also happen if your committer email address is not on your profile.

**Review by andrewazores — COMMENTED** [review]
Should the `go.mod` cert-manager version also be updated then?

**Review by ebaron — COMMENTED** [review]
Thanks @tthvo! I would update the version in `go.mod` as Andrew suggested and then run `go mod tidy`.

**Comment by tthvo** [comment]
Updated now! Seems like it also requires version bumps in other k8s modules. Should we wait till #614 to use `1.12.4`?

> @tthvo I see your commits are signed but unverified.

Opps sorry laptop crashed last night and had to reinstall Fedora :(( So lost the old keys. Signed again now :))

**Comment by andrewazores** [comment]
It might be better to wait - assuming that the Operator SDK upgrade is also going to upgrade the k8s modules to those same versions.

Did 1.11.5 not need to update those?

**Comment by tthvo** [comment]
Seems to break the tests too. Yeh, `1.11.5` does not require any other upgrades.

**Comment by tthvo** [comment]
Not sure why the image is not available after successful push: https://github.com/cryostatio/cryostat-operator/actions/runs/6126153972/job/16629579344?pr=622

Checked here but can't see it either: https://github.com/orgs/cryostatio/packages/container/package/cryostat-operator-bundle

**Comment by andrewazores** [comment]
That is weird. The CI runner logs do report that it successfully pushed an image with that tag to ghcr.io . Could be a ghcr.io infra thing.

**Comment by tthvo** [comment]
Yehh no idea :)) I can't rerun actions tho. Can u help..?

**Comment by andrewazores** [comment]
Trying a rerun of the same one you posted now.

**Comment by tthvo** [comment]
Now, the image is available :)) very odd haha...

**Review by ebaron — COMMENTED** [review]
https://github.com/cryostatio/cryostat-operator/issues/614 doesn't seem to bump the k8s dependencies at all. Even the current HEAD is using 0.26.0: https://github.com/operator-framework/operator-sdk/blob/8ceb4e07c2e0b7f5cac16b3b82817636c830fbac/testdata/go/v3/memcached-operator/go.mod#L8-L10.

I think it's probably best to stick with cert-manager 1.11.5 for now. Feel free to update the k8s depedencies in go.mod to 0.26.4 to sync with what cert-manager uses. Patch releases shouldn't cause us any trouble.

**Comment by ebaron** [comment]
@tthvo Could I get you to upgrade the k8s deps to 0.26.8 actually? And run `go mod tidy` again?

**Comment by tthvo** [comment]
Sure make sense to me! Updated now ^^

**Review by ebaron — APPROVED** [review]
Looks good! I'm liking those updated transitive deps.

**Comment by ebaron** [comment]
Thanks @tthvo for taking the time to do this. Much appreciated!

**Comment by tthvo** [comment]
Thanks I am happy to help anytime :))

**Pull request merged**
