### PR TITLE
fix(crd): fix OLM descriptors and documentation 

### PR DESCRIPTION
**Pull request by ebaron**
This PR fixes the issue where the OLM spec descriptor would require an integer value for Recording duration. It's now a string and the description has been updated to indicate the format it should be. I've also added a proper description for each CRD, instead of "x is the schema for the x API". These are displayed to the user right away after installing the operator. I also corrected field descriptions that no longer make sense, like the event options field is no longer using the event specifier string format.

Finally, I wanted to leverage the same mechanism that lists local Secrets and Config Maps to list local FlightRecorder objects when creating a Recording. Because the FlightRecorder name is within a LocalObjectReference, I wasn't able to do this with Operator SDK's markers. I instead added a small Kustomize patch to add the spec descriptor and modify the path to `flightRecorder.name`.

I created a bundle image for easy testing: `quay.io/ebaron/cryostat-operator-bundle:crd-metadata-fixes`

Fixes: #256

### CODE REVIEW

**Comment by andrewazores** [comment]
Code changes look good to me. I'll deploy that bundle and manually test it out soon.

**Comment by andrewazores** [comment]
Aside:

```makefile
BUNDLE_IMG ?= $(IMAGE_NAMESPACE)/$(OPERATOR_NAME)-bundle:$(BUNDLE_VERSION)

# Build the bundle image.
.PHONY: bundle-build
bundle-build:
	$(IMAGE_BUILDER) build -f bundle.Dockerfile -t $(BUNDLE_IMG) .

.PHONY: deploy_bundle
deploy_bundle: check_cert_manager undeploy_bundle
	operator-sdk run bundle $(IMAGE_NAMESPACE)/$(OPERATOR_NAME)-bundle:$(IMAGE_VERSION)
```

Should `deploy_bundle` use `BUNDLE_IMG`, too? It's the same thing in the default case.

**Comment by andrewazores** [comment]
Having weird issues with my crc at the moment. I'll try again tomorrow.

```
operator-sdk cleanup cryostat-operator
INFO[0000] catalogsource "cryostat-operator-catalog" deleted 
INFO[0000] Operator "cryostat-operator" uninstalled     
operator-sdk run bundle quay.io/ebaron/cryostat-operator-bundle:crd-metadata-fixes
INFO[0096] Successfully created registry pod: quay-io-ebaron-cryostat-operator-bundle-crd-metadata-fixes 
INFO[0096] Created CatalogSource: cryostat-operator-catalog 
INFO[0096] OperatorGroup "operator-sdk-og" created      
INFO[0096] Created Subscription: cryostat-operator-v2-1-0-dev-sub 
INFO[0119] Approved InstallPlan install-mfv5k for the Subscription: cryostat-operator-v2-1-0-dev-sub 
INFO[0119] Waiting for ClusterServiceVersion "myproject/cryostat-operator.v2.1.0-dev" to reach 'Succeeded' phase 
INFO[0119]   Waiting for ClusterServiceVersion "myproject/cryostat-operator.v2.1.0-dev" to appear 
FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition 
make: *** [Makefile:212: deploy_bundle] Error 1
```

**Comment by ebaron** [comment]
> Aside:
> 
> ```makefile
> BUNDLE_IMG ?= $(IMAGE_NAMESPACE)/$(OPERATOR_NAME)-bundle:$(BUNDLE_VERSION)
> 
> # Build the bundle image.
> .PHONY: bundle-build
> bundle-build:
> 	$(IMAGE_BUILDER) build -f bundle.Dockerfile -t $(BUNDLE_IMG) .
> 
> .PHONY: deploy_bundle
> deploy_bundle: check_cert_manager undeploy_bundle
> 	operator-sdk run bundle $(IMAGE_NAMESPACE)/$(OPERATOR_NAME)-bundle:$(IMAGE_VERSION)
> ```
> 
> Should `deploy_bundle` use `BUNDLE_IMG`, too? It's the same thing in the default case.

Yes definitely. I filed #226 a while back as a good first issue.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
