### PR TITLE
ci(dependabot): configure dependabot updates

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #537 

## Description of the change:

Configure dependabot updates to ignore k8s related deps. These deps will be upgrade with operator-sdk upgrades.

## Motivation for the change:

See #537

### CODE REVIEW

**Comment by tthvo** [comment]
Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

**Comment by andrewazores** [comment]
I think this makes sense but I defer to @ebaron .

**Review by ebaron — COMMENTED** [review]
Thanks for doing this @tthvo! For the k8s dependencies, this will have the effect of only updating patch releases right?

**Comment by ebaron** [comment]
> Hi yes, I believe so.
> 
> > By default all dependencies that are explicitly defined in a manifest are kept up to date by Dependabot version updates.
> 
> > You can use allow and ignore to customize which dependencies to maintain. Dependabot checks for all allowed dependencies and then filters out any ignored dependencies or versions. So a dependency that is matched by both an allow and an ignore will be ignored.
> 
> So, unless specified with `version-update:semver-patch` in `ignore`, the deps should receive patch update.

Excellent, thank you!

**Review by ebaron — APPROVED** [review]

**Pull request merged**
