### PR TITLE
feat(service): add part-of, instance selector labels and appProtocol

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #<issue number>
See https://github.com/cryostatio/cryostat-helm/pull/211
Related to https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/2

## Description of the change:
*This change adds allows the users to provide...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Insert steps here...*
2. *...*

### CODE REVIEW

**Comment by andrewazores** [comment]
image

This PR + https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/2 leads to this situation. The Cryostat Service is correctly identified, but the Agent proxy service is, too. That proxy has the same `component: cryostat` label on it - @ebaron does anything depend on that as a selector at this point, or can we change it?

**Comment by ebaron** [comment]
> @ebaron does anything depend on that as a selector at this point, or can we change it?

Nothing relies on this, so renaming should be fine.

**Comment by andrewazores** [comment]
I wonder if I can still do this -

**Pull request merged**
