### PR TITLE
chore(api): remove minimal option from CR spec

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #728 

## Description of the change:

- Removed minimal mode support in v1beta2 API.
  - I left the network resources (i.e. ingress, route) for grafana intact utill #727 that deploy cryostat3 behind proxy.

## Motivation for the change:

See #728 

## How to manually test:

Set up and rebuild images:

```bash
export IMAGE_NAMESPACE=quay.io/<namespace>
export IMAGE_VERSION=3.0.0-remove-minimal
make oci-build bundle bundle-build
podman push quay.io/<namespace>/cryostat-operator:$IMAGE_VERSION
podman push quay.io/<namespace>/cryostat-operator-bundle:$IMAGE_VERSION
make deploy_bundle
```

**With OpenShift:**

```bash
yq .spec.minimal=true config/samples/operator_v1beta1_cryostat.yaml | oc apply -f -
```

**With k8s (and Nginx Ingress Controller):**

Create a CR with the following specs in this [https://gist.github.com/tthvo/4be15d6ad0b52c5e1d6ee6f053f12371](https://gist.github.com/tthvo/4be15d6ad0b52c5e1d6ee6f053f12371).

```bash
kubectl apply -f <path-to-cr.yaml>
```

Watch the beta1 CR converted to beta2 without minimal mode and the k8s resources are created correctly as in non-minimal mode.

### CODE REVIEW

**Review by ebaron — COMMENTED** [review]
Hey @tthvo, code looks great! Just need to resolve a couple conflicts after #743.

**Comment by tthvo** [comment]
Updated and resolved conflicts now :D

**Review by ebaron — APPROVED** [review]
Thanks @tthvo!

**Pull request merged**
