### PR TITLE
test(proxy): add missing args to proxy expectations

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits): `git commit -S -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Related to #844 #839

## Description of the change:
*This change adds allows the users to provide...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Insert steps here...*
2. *...*

### CODE REVIEW

**Review by tthvo — APPROVED** [review]
Nice catch! My branch was probably still behind cryostat3 in #844 :D

**Comment by andrewazores** [comment]
Yep exactly. The branch protection rule that warns against this kind of "branch out of date" problem is only set up to apply to `main` and `cryostat-vX.Y` release branches, so it didn't appear on that PR.

**Comment by tthvo** [comment]
Ahh make sense! I got the false impression that it was update-to-date...Thanks!

**Pull request merged**
