### PR TITLE
chore(build): add short summaries to targets

### LINKED ISSUE #634: [Request] Makefile should have short summaries for targets
### Describe the feature

This would be helpful to contributors to not have to check the Makefile:

```
$ make help
Usage:
  make <target>
  help             Display this help.
  oci-buildx       Build OCI image for the manager for cross-platform support
  operator-sdk     Download operator-sdk locally if necessary.
```

### Anything other information?

Operator-sdk scaffold sets this up so we can sync with them.

https://github.com/operator-framework/operator-sdk/blob/e67da35ef4fff3e471a208904b2a142b27ae32b1/testdata/go/v3/memcached-operator/Makefile#L86

Each target needs trailing comments on target definition line, for example:

https://github.com/operator-framework/operator-sdk/blob/e67da35ef4fff3e471a208904b2a142b27ae32b1/testdata/go/v3/memcached-operator/Makefile#L93

### PR DESCRIPTION
**Pull request by andrewazores**
See #636
Fixes #634 

I used the git reflog and attempted to cherry-pick the correct changes back together after failing to properly rebase @pektezol 's previous PR. This PR is a backup in case the original one cannot be fully recovered.

### CODE REVIEW

**Comment by andrewazores** [comment]
@pektezol @tthvo sorry about that. If @pektezol 's original PR can't be recovered and reopened easily then please double-check my work attempting to recover it here.

**Review by tthvo — APPROVED** [review]
Looks good to me! I think we can move the work to this PR then to ease the recover process.

**Comment by tthvo** [comment]
Maybe also link #634 to automatically close it?

**Comment by pektezol** [comment]
Damn what happened here lol. Oh well.

**Comment by pektezol** [comment]
Any update on this pr? @tthvo

**Comment by andrewazores** [comment]
It looks good to me (and @tthvo too I think), but I tagged @ebaron for review since he's the primary maintainer of this repository. He's been busy with other tasks in the meantime.

**Review by ebaron — APPROVED** [review]
Very cool, thanks @pektezol!

**Pull request merged**
