### PR TITLE
docs(cert-manager): Add cert-manager docs to CSV

### LINKED ISSUE #299: Document cert-manager usage in CSV
Mention the cert-manager dependency for the operator and point cert-manager's installation docs: https://cert-manager.io/docs/installation/.

This should go in the CSV's `spec.description`, which supports Markdown syntax, so in theory we can add links and paragraph breaks.

### PR DESCRIPTION
**Pull request by jan-law**
Fixes #299 

Docs were copied from https://cryostat.io/get-started/

Operator Preview:
image

### CODE REVIEW

**Comment by jan-law** [comment]
Since this PR gets merged to the main branch, what's the best way to include this change in the 2.0.0 bundle that I want to contribute to OperatorHub.io?

**Review by ebaron — APPROVED** [review]
Looks great, thanks Janelle! I've also requested a backport, since this is a text-only change and will be a helpful reminder to users.

**Comment by ebaron** [comment]
> Since this PR gets merged to the main branch, what's the best way to include this change in the 2.0.0 bundle that I want to contribute to OperatorHub.io?

If there are no other modifications we need to make, it might be easiest to just patch the CSV description manually in your fork of the OperatorHub repo.

**Comment by ebaron** [comment]
It's okay to leave it as-is though, and include any fixes in a potential 2.0.1 release on OperatorHub.io.

**Pull request merged**
