### PR TITLE
test(sample): update sample apps

### PR DESCRIPTION
**Pull request by andrewazores**
Related to #485

### CODE REVIEW

**Review by ebaron — APPROVED** [review]

**Comment by tthvo** [comment]
Sorry a bit late on this, but just noticed `quarkus-test` is not using JMX auth while checking on Cryostat web console?

**Comment by andrewazores** [comment]
We could add it in there, but it would need another update to the app container to add the `jmxremote.password` and `jmxremote.access` files like what `vertx-fib-demo` has.

**Comment by tthvo** [comment]
Ah right! Are we planning to add them in or Is this quarkus-test meant to have SSL enabled while vertx has Auth for this sample app setup?

**Comment by andrewazores** [comment]
`vertx-fib-demo` can do both auth and SSL, it just needs env vars set to enable them (https://github.com/cryostatio/cryostat/blob/e97ecb1915af7218c3a3d3f9ed784e0520caaba2/smoketest.sh#L82). `quarkus-test` isn't built/configured with support for either of those things, it's just there as a placeholder for a second testing application right now. It can also be configured to act as a discovery plugin though, and it also has an early build of the Cryostat Agent (discovery plugin impl only) baked in, so it's useful for testing those components.

Adding more make recipes to deploy different instances of each app with each of these different configs would be cool.

**Comment by tthvo** [comment]
Right that makes sense! Also, wondering what is keeping #485 open?

> Adding more make recipes to deploy different instances of each app with each of these different configs would be cool.

That would very nice! Just have to see how #454 turns out :D

**Comment by andrewazores** [comment]
#485 is still open because there's only JMX auth on the one sample app after this PR, but there is still not test case for SSL. I think that's important enough to have the issue remain open.

**Pull request merged**
